### ISSUE TITLE
Change from Decision --- > Promotion 

### ISSUE THREAD

**Issue by lamtranpartners** [Vice-App/web-frontend#12]

**Comment by lamtranpartners** [comment]
Je peux telecharger?

On Sunday 10 April 2016, Aymeric Matencio notifications@github.com wrote:

> Closed #12 https://github.com/Vice-App/web-frontend/issues/12.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/12#event-621160560

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205

**Comment by aymericatvice** [comment]
yes jallais tenvoyer en rar par mail mais gogo

**Comment by lamtranpartners** [comment]
Vas y par mail :)

On Sunday 10 April 2016, Aymeric Matencio notifications@github.com wrote:

> yes jallais tenvoyer en rar par mail mais gogo
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/12#issuecomment-207819192

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205

**Comment by aymericatvice** [comment]
done!
