### ISSUE TITLE
Payment by Transfer

### ISSUE THREAD

**Issue by lamtranpartners** [Vice-App/web-frontend#5]
For Bank Transfer

Why? 

We need to send the money back to you whenever you launch a campaign where you require our users to make a payment on our app.

The money is sent back to your bank account every 15 calendar days

**Comment by aymericatvice** [comment]
"When you launch a campaign where users are required to make a purchase on Vice App, we need to send you the money back. This is done by bank transfer to the account you provide here, every 15 calendar days."

**Comment by lamtranpartners** [comment]
Good

On Saturday 26 March 2016, Aymeric Matencio notifications@github.com
wrote:

> "When you launch a campaign where users are required to make a purchase on
> Vice App, we need to send you the money back. This is done by bank transfer
> to the account you provide here, every 15 calendar days."
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/5#issuecomment-201825827

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205
