### ISSUE TITLE
Direct Debit Payment

### ISSUE THREAD

**Issue by lamtranpartners** [Vice-App/web-frontend#6]
Payment by Card

Why?

For campaigns that require our users to scan, we will charge upfront 100 scans and every subsequent 100 scans. 

The card information is processed directly by Cybersource Inc. a Visa Inc. company. We never store or hold your information on our servers.

**Comment by aymericatvice** [comment]
"When you launch a campaign where users are required to (#)redeem a Vice Code, Vice App will charge 100 codes upfront and every 100 codes thereafter . This is done by Direct Debit.

The card information is processed directly by CyberSource Inc. a Visa Inc. company. We never store or hold your information on our servers."

Explanation

# Scan = 1 way to Redeem a Vice code

# Beacon checkin  = Another way to Redeem

Together = Redeem a Vice Code

**Comment by aymericatvice** [comment]
tien bizarre quand je commence une ligne avec # ca me le met en Heading 1
