### ISSUE TITLE
Add during the registration 3 more required fields

### ISSUE THREAD

**Issue by lamtranpartners** [Vice-App/web-frontend#7]
Contact Point

First Name 
Last Name 

Cell Phone Number :

**Comment by aymericatvice** [comment]
Shouldn't it be at Registration ?

**Comment by lamtranpartners** [comment]
For what?

On Saturday 26 March 2016, Aymeric Matencio notifications@github.com
wrote:

> Shouldn't it be at Registration ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/7#issuecomment-201804733

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205

**Comment by aymericatvice** [comment]
Register the Contact Point at the same time as Username/password?

**Comment by lamtranpartners** [comment]
Could be

Or add another step so we don't overwhelm people

On Saturday 26 March 2016, Aymeric Matencio notifications@github.com
wrote:

> Register the Contact Point at the same time as Username/password?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/7#issuecomment-201813497

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205

**Comment by aymericatvice** [comment]
It's B2B registration, not random dudes...

**Comment by lamtranpartners** [comment]
Maybe... But I don't know... I'm kinda indecisive and think about people's
feelings that's why

Easier to code for you or what?

On Saturday 26 March 2016, Aymeric Matencio notifications@github.com
wrote:

> It's B2B registration, not random dudes...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/7#issuecomment-201814174

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205

**Comment by aymericatvice** [comment]
Same. 
Question: we split the payment methods into 2 steps : bank account / card info
How should we name them? Currently both were under : Register Payment Method

**Comment by lamtranpartners** [comment]
Gotta figure this out Mr Matencio...

More and more questions just put something random first and make it work.

Content can be provided thereafter as it's quicker to fix

On Saturday 26 March 2016, Aymeric Matencio notifications@github.com
wrote:

> Same.
> Question: we split the payment methods into 2 steps : bank account / card
> info
> How should we name them? Currently both were under : Register Payment
> Method
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vice-App/web-frontend/issues/7#issuecomment-201822749

## 

Lam Tran

CEO
Vice
Vincom Center
12A Floor, 72 Le Thanh Ton
Ben Nghe Ward, District 1
HCMC

Tel : +84 965 878 205
